### ISSUE TITLE
Failed to connect to X11, when running as system service

### ISSUE THREAD

**Issue by toothbrush** [xremap/nix-flake#55]
Hi! :wave: I've probably configured something wrong, so please let me know if this isn't appropriate for the issue tracker.

My issue is that having configured xremap in NixOS using this flake, my "application dependent" remaps initially don't work.  The logs in `journalctl -u xremap` have entries like this:

```
Dec 23 12:24:47 kuti xremap[1495]: $DISPLAY is not set. Defaulting to DISPLAY=:0
Dec 23 12:24:47 kuti xremap[1495]: warning: Failed to connect to X11: X11 setup failed: 'Authorization required, but no authorization protocol specified
Dec 23 12:24:47 kuti xremap[1495]: '
Dec 23 12:24:47 kuti xremap[1495]: If you saw "No protocol specified", try running `xhost +SI:localuser:root`.
Dec 23 12:24:47 kuti xremap[1495]: If not, make sure `echo $DISPLAY` outputs xremap's $DISPLAY (:0).
Dec 23 12:24:47 kuti xremap[1495]: application-client: X11 (supported: false)
```

Otherwise, xremap is working well.  I can solve the issue by manually running the suggested `xhost` incantation as myself, and restarting xremap:

```shellsession
$ nix-shell -p xorg.xhost

[nix-shell:~]$ xhost +SI:localuser:root
localuser:root being added to access control list

[nix-shell:~]$ sudo systemctl restart xremap
```

After that, things work well.  I'm wondering whether there's a way to get xremap configured so it works out of the box, because i guess my alternative is to add a one-shot script to my systemctl so that it executes the `xhost` command when i log into my X session.  But that feels pretty hacky.

I'll paste the relevant configuration.

My `/etc/nixos/flake.nix`:

```nix
{
  description = "My NixOS Flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.11";
    xremap-flake.url = "github:xremap/nix-flake";
  };

  outputs = { self, nixpkgs, ... }@inputs: {
    nixosConfigurations.kuti = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
        inputs.xremap-flake.nixosModules.default
        {
          services.xremap = {
            serviceMode = "system";
            withX11 = true;
            yamlConfig = (builtins.readFile ./keyboard/xremap.yaml);
          };
        }
      ];
    };
  };
}
```

The referenced `/etc/nixos/keyboard/xremap.yaml` (i've stripped away a lot of redundant things that aren't relevant to this issue, let me know if you need more details):

```yaml
keymap:
  - name: Emacs
    application:
      not:
        - Emacs
        - URxvt
    remap:
      # Kill line
      C-k: [Shift-end, C-x, { set_mark: false }]
      C-u: [home, Shift-end, C-x, { set_mark: false }]
      # Kill word backward
      C-w: [C-backspace, {set_mark: false}]

modmap:
  - name: Global
    remap:
      # swap left alt & super
      Alt_L: Super_L
      Super_L: Alt_L
```

With this configuration, the symptom is that in my terminal (urxvt) i cannot use `C-w`, until i fix the `xhost` thing -- then things work correctly.

I hope this makes sense! :pray:
