### ISSUE TITLE
Application-specific remapping does not work

### ISSUE THREAD

**Issue by idiig** [xremap/nix-flake#63]
I'm using NixOS with xfce4 and xmonad. It seems that my key remapping works globally, even in applications I intended to exclude in my configuration. Do you have any suggestions on how to resolve this?

The related configurations are as follows:

```
_:
{
  services.xremap = {
    serviceMode = "system";
    yamlConfig = builtins.readFile ./remap.yml;
    debug = true;
    withX11 = true;
  };
}
```

`./remap.yml` basically follows [this example](https://github.com/xremap/xremap/blob/master/example/emacs.yml)

```
modmap:
- name: CtrlRemap
  remap:
    Capslock :
      held: Ctrl_L
      alone: Esc
      alone_timeout_millis: 1000
    Esc: Capslock

keymap:
- name: Emacs
  application:
    not: [Emacs, Code, Xfce4-terminal]
  remap:
    # Cursor
    C-b: { with_mark: left }
    C-f: { with_mark: right }
    C-p: { with_mark: up }
    C-n: { with_mark: down }
    # Forward/Backward word
    M-b: { with_mark: C-left }
    M-f: { with_mark: C-right }
    # Beginning/End of line
    C-a: { with_mark: home }
    C-e: { with_mark: end }
    # Page up/down
    M-v: { with_mark: pageup }
    C-v: { with_mark: pagedown }
    # Beginning/End of file
    M-Shift-comma: { with_mark: C-home }
    M-Shift-dot: { with_mark: C-end }
    # Newline
    C-m: enter
    C-j: enter
    C-o: [enter, left]
    # Copy
    C-w: [C-x, { set_mark: false }]
    M-w: [C-c, { set_mark: false }]
    C-y: [C-v, { set_mark: false }]
    # Delete
    C-d: [delete, { set_mark: false }]
    M-d: [C-delete, { set_mark: false }]
    C-h: [backspace, { set_mark: false }]
    # Kill line
    C-k: [Shift-end, C-x, { set_mark: false }]
    # Kill word backward
    Alt-backspace: [C-backspace, {set_mark: false}]
    # set mark next word continuously.
    C-M-space: [C-Shift-right, {set_mark: true}]
    # Undo
    C-slash: [C-z, { set_mark: false }]
    C-Shift-ro: C-z
    # Mark
    C-space: { set_mark: true }
    # Search
    C-s: C-f
    C-r: Shift-F3
    M-Shift-5: C-h
    # Cancel
    C-g: [esc, { set_mark: false }]
    # C-x YYY
    C-x:
      remap:
        # C-x h (select all)
        h: [C-home, C-a, { set_mark: true }]
        # C-x C-f (open)
        C-f: C-o
        # C-x C-s (save)
        C-s: C-s
        # C-x k (kill tab)
        k: C-f4
        # C-x C-c (exit)
        C-c: C-q
        # C-x u (undo)
        u: [C-z, { set_mark: false }]
 ```
